

package ec.edu.espe.store.view;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author alejandro
 */
public class FrmCatalogue extends javax.swing.JFrame {
    
   

    /** Creates new form VerCatalogo */
    public FrmCatalogue() {
        initComponents();
        sizeImage();
        this.setLocationRelativeTo(null);
        
    }
    
    public void sizeImage(){
        ImageIcon imagen1= new ImageIcon(getClass().getResource("/images/BLSTPYG1209B-1.jpg"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(LbBlender.getWidth(), LbBlender.getHeight(), Image.SCALE_DEFAULT));
        LbBlender.setIcon(fondo1);
        ImageIcon imagen2= new ImageIcon(getClass().getResource("/images/cafetera-digital-programable-con-filtro-permanente-12-tazas-1000w-black-decker.jpg"));
        Icon fondo2 = new ImageIcon(imagen2.getImage().getScaledInstance(LbCoffeeMarker.getWidth(), LbCoffeeMarker.getHeight(), Image.SCALE_DEFAULT));
        LbCoffeeMarker.setIcon(fondo2);
        ImageIcon imagen3= new ImageIcon(getClass().getResource("/images/mejores-laptops-2020.jpg"));
        Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(LbComputer.getWidth(), LbComputer.getHeight(), Image.SCALE_DEFAULT));
        LbComputer.setIcon(fondo3);
        ImageIcon imagen4= new ImageIcon(getClass().getResource("/images/led-43-smart-tv-motorola-flc01.jpg"));
        Icon fondo4 = new ImageIcon(imagen4.getImage().getScaledInstance(LBTvs.getWidth(), LBTvs.getHeight(), Image.SCALE_DEFAULT));
        LBTvs.setIcon(fondo4);
        ImageIcon imagen5= new ImageIcon(getClass().getResource("/images/latin-microwave-oven-solo-ms23j5133am-ms23j5133am-ap-001-front.png"));
        Icon fondo5 = new ImageIcon(imagen5.getImage().getScaledInstance(LbMicrowave.getWidth(), LbMicrowave.getHeight(), Image.SCALE_DEFAULT));
        LbMicrowave.setIcon(fondo5);
        ImageIcon imagen6= new ImageIcon(getClass().getResource("/images/71WE-THHg7S._AC_SS450_.jpg"));
        Icon fondo6 = new ImageIcon(imagen6.getImage().getScaledInstance(LbToater.getWidth(), LbToater.getHeight(), Image.SCALE_DEFAULT));
        LbToater.setIcon(fondo6);
        ImageIcon imagen7= new ImageIcon(getClass().getResource("/images/120551_01.jpg"));
        Icon fondo7 = new ImageIcon(imagen7.getImage().getScaledInstance(LbFridge.getWidth(), LbFridge.getHeight(), Image.SCALE_DEFAULT));
        LbFridge.setIcon(fondo7);
        ImageIcon imagen8= new ImageIcon(getClass().getResource("/images/Home-Appliance-with-1600W-Quartz-Heater-Bluetooth-Heater-Outdoor-Heater-Infrared-Heater.jpg"));
        Icon fondo8 = new ImageIcon(imagen8.getImage().getScaledInstance(LbHaiter.getWidth(), LbHaiter.getHeight(), Image.SCALE_DEFAULT));
        LbHaiter.setIcon(fondo8);
        ImageIcon imagen9= new ImageIcon(getClass().getResource("/images/D_NQ_NP_818838-MCO31767455378_082019-O.jpg"));
        Icon fondo9 = new ImageIcon(imagen9.getImage().getScaledInstance(LbDvd.getWidth(), LbDvd.getHeight(), Image.SCALE_DEFAULT));
        LbDvd.setIcon(fondo9);
        
        
    }
    
    private void eventosNodoSeleccionado(DefaultMutableTreeNode nodoSeleccionado){
        if(nodoSeleccionado.toString().equals("Fungicidas")){
            //etiquetaImagen.setIcon(new ImageIcon(getClass().getResource("C:/Users/alejandro/Desktop/drive-download-20210807T170843Z-001/Proyecto POO/ProyectoAplicacion/imagenFungicida")));
            //etiquetaNombreImagen.setText("FUNGICIDA");
            //cajaNombre.setText("FUNGICIDA");
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        etiquetaAgroquimicos = new javax.swing.JLabel();
        LbBlender = new javax.swing.JLabel();
        imagenFungicida = new javax.swing.JLabel();
        imagenInsecticida = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        etiquetaFertilizantesyEdaficos = new javax.swing.JLabel();
        imagenFertilizanteSolubleAgua = new javax.swing.JLabel();
        imagenAbonoFOliar = new javax.swing.JLabel();
        LbToater = new javax.swing.JLabel();
        imagenFijayReguPh = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        etiquetaFumigacion = new javax.swing.JLabel();
        LbCoffeeMarker = new javax.swing.JLabel();
        imagenBombaFumigacion = new javax.swing.JLabel();
        BtnReturn = new javax.swing.JButton();
        etiquetaAgroquimicos1 = new javax.swing.JLabel();
        LbComputer = new javax.swing.JLabel();
        etiquetaAgroquimicos2 = new javax.swing.JLabel();
        LBTvs = new javax.swing.JLabel();
        etiquetaFertilizantesyEdaficos1 = new javax.swing.JLabel();
        LbMicrowave = new javax.swing.JLabel();
        etiquetaFertilizantesyEdaficos2 = new javax.swing.JLabel();
        LbDvd = new javax.swing.JLabel();
        etiquetaFumigacion1 = new javax.swing.JLabel();
        etiquetaFumigacion2 = new javax.swing.JLabel();
        LbFridge = new javax.swing.JLabel();
        LbHaiter = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(450, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 1653));

        etiquetaAgroquimicos.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        etiquetaAgroquimicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaAgroquimicos.setText("LICUADORAS");

        LbBlender.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        LbBlender.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiquetaFertilizantesyEdaficos.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        etiquetaFertilizantesyEdaficos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaFertilizantesyEdaficos.setText("TOSTADORES");

        LbToater.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        LbToater.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiquetaFumigacion.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        etiquetaFumigacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaFumigacion.setText("CAFETERAS");

        LbCoffeeMarker.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        LbCoffeeMarker.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnReturn.setBackground(new java.awt.Color(255, 255, 255));
        BtnReturn.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        BtnReturn.setText("Regresar");
        BtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturnActionPerformed(evt);
            }
        });

        etiquetaAgroquimicos1.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        etiquetaAgroquimicos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaAgroquimicos1.setText("COMPUTADORES");

        LbComputer.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        LbComputer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiquetaAgroquimicos2.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        etiquetaAgroquimicos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaAgroquimicos2.setText("TVS");

        LBTvs.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        LBTvs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiquetaFertilizantesyEdaficos1.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        etiquetaFertilizantesyEdaficos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaFertilizantesyEdaficos1.setText("MICROONDAS");

        LbMicrowave.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        LbMicrowave.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiquetaFertilizantesyEdaficos2.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        etiquetaFertilizantesyEdaficos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaFertilizantesyEdaficos2.setText("DVD");

        LbDvd.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        LbDvd.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiquetaFumigacion1.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        etiquetaFumigacion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaFumigacion1.setText("REFRIGERADORES");

        etiquetaFumigacion2.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        etiquetaFumigacion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaFumigacion2.setText("CALENTADORES DOMESTICOS");

        LbFridge.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        LbFridge.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LbHaiter.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        LbHaiter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Ver Modelos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaFumigacion, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LbCoffeeMarker, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaFumigacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbFridge, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaFumigacion2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(imagenBombaFumigacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbHaiter, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separador1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LbBlender, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAgroquimicos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LbComputer, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imagenFungicida)
                            .addComponent(imagenInsecticida)))
                    .addComponent(etiquetaAgroquimicos1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBTvs, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAgroquimicos2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(imagenFijayReguPh))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(LbToater, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(LbMicrowave, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagenFertilizanteSolubleAgua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imagenAbonoFOliar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbDvd, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(etiquetaFertilizantesyEdaficos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(etiquetaFertilizantesyEdaficos1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(etiquetaFertilizantesyEdaficos2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(imagenFungicida)
                        .addGap(142, 142, 142)
                        .addComponent(imagenInsecticida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaAgroquimicos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaAgroquimicos1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaAgroquimicos2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbBlender, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbComputer, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBTvs, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFertilizantesyEdaficos)
                    .addComponent(etiquetaFertilizantesyEdaficos1)
                    .addComponent(etiquetaFertilizantesyEdaficos2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(imagenFertilizanteSolubleAgua)
                        .addGap(146, 146, 146)
                        .addComponent(imagenAbonoFOliar)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbMicrowave, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbToater, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbDvd, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addComponent(imagenFijayReguPh)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(imagenBombaFumigacion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaFumigacion)
                            .addComponent(etiquetaFumigacion1)
                            .addComponent(etiquetaFumigacion2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbCoffeeMarker, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbFridge, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbHaiter, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturnActionPerformed
        FrmMenu menu = new FrmMenu();
        menu.setVisible(true);
        dispose();

    }//GEN-LAST:event_BtnReturnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmViewProducts frmViewProducts = new FrmViewProducts();
        frmViewProducts.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCatalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCatalogue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReturn;
    private javax.swing.JLabel LBTvs;
    private javax.swing.JLabel LbBlender;
    private javax.swing.JLabel LbCoffeeMarker;
    private javax.swing.JLabel LbComputer;
    private javax.swing.JLabel LbDvd;
    private javax.swing.JLabel LbFridge;
    private javax.swing.JLabel LbHaiter;
    private javax.swing.JLabel LbMicrowave;
    private javax.swing.JLabel LbToater;
    private javax.swing.JLabel etiquetaAgroquimicos;
    private javax.swing.JLabel etiquetaAgroquimicos1;
    private javax.swing.JLabel etiquetaAgroquimicos2;
    private javax.swing.JLabel etiquetaFertilizantesyEdaficos;
    private javax.swing.JLabel etiquetaFertilizantesyEdaficos1;
    private javax.swing.JLabel etiquetaFertilizantesyEdaficos2;
    private javax.swing.JLabel etiquetaFumigacion;
    private javax.swing.JLabel etiquetaFumigacion1;
    private javax.swing.JLabel etiquetaFumigacion2;
    private javax.swing.JLabel imagenAbonoFOliar;
    private javax.swing.JLabel imagenBombaFumigacion;
    private javax.swing.JLabel imagenFertilizanteSolubleAgua;
    private javax.swing.JLabel imagenFijayReguPh;
    private javax.swing.JLabel imagenFungicida;
    private javax.swing.JLabel imagenInsecticida;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator separador1;
    // End of variables declaration//GEN-END:variables

}
