/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.store.view;

import ec.edu.espe.store.model.Client;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.bson.Document;
import utils.DatabaseConnection;
import utils.FileManager;
import utils.InputValidation;

/**
 *
 * @author Nicolas Suquillo NullPointers ESPE-DCCO
 */
public class FrmRegisterClient extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegisterClient
     */
    public FrmRegisterClient() {
        initComponents();
        setWarnings();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        chkMen = new javax.swing.JCheckBox();
        chkWoman = new javax.swing.JCheckBox();
        chkOthers = new javax.swing.JCheckBox();
        lblWarningName = new javax.swing.JLabel();
        lblWarningLastName = new javax.swing.JLabel();
        lblWarningId = new javax.swing.JLabel();
        lblWarningGender = new javax.swing.JLabel();
        lblWarningAge = new javax.swing.JLabel();
        lblWarningPhoneNumber = new javax.swing.JLabel();
        lblWarningAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblWarningEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Registrar Cliente");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Nombres :");

        txtName.setToolTipText("Ej: \"Francisco Nicolás\"");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Cédula :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Género :");
        jLabel5.setToolTipText("Elija solo un genero");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Edad :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Telefono :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Dirección :");

        txtId.setToolTipText("Ej: \"1753344265\"");

        txtLastName.setToolTipText("Ej: \"Suquillo Gavilanes\"");

        txtAge.setToolTipText("Ej: \"20\"");

        txtPhoneNumber.setToolTipText("Ej: \"0983744526\"");

        btnSave.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClean.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnClean.setText("Limpiar");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setText("Regresar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        chkMen.setText("Hombre");

        chkWoman.setText("Mujer");

        chkOthers.setText("Otros");

        lblWarningName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWarningName.setForeground(java.awt.Color.red);
        lblWarningName.setText("*");

        lblWarningLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWarningLastName.setForeground(java.awt.Color.red);
        lblWarningLastName.setText("*");

        lblWarningId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWarningId.setForeground(java.awt.Color.red);
        lblWarningId.setText("*");

        lblWarningGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWarningGender.setForeground(java.awt.Color.red);
        lblWarningGender.setText("*");

        lblWarningAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWarningAge.setForeground(java.awt.Color.red);
        lblWarningAge.setText("*");

        lblWarningPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWarningPhoneNumber.setForeground(java.awt.Color.red);
        lblWarningPhoneNumber.setText("*");

        lblWarningAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWarningAddress.setForeground(java.awt.Color.red);
        lblWarningAddress.setText("*");

        txtAddress.setToolTipText("Omitir numeros - Ej: \"Quito, Eloy Alfaro\" ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Email :");

        lblWarningEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWarningEmail.setForeground(java.awt.Color.red);
        lblWarningEmail.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(151, 151, 151))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnClean)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblWarningName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblWarningLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblWarningId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblWarningGender, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblWarningAge, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtLastName)
                                        .addComponent(txtId)
                                        .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chkMen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkWoman)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkOthers)))))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWarningPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWarningAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWarningEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarningName)
                    .addComponent(lblWarningPhoneNumber))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarningLastName)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarningAddress))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarningId)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarningEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(chkMen)
                    .addComponent(chkWoman)
                    .addComponent(chkOthers)
                    .addComponent(lblWarningGender))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarningAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClean)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed

        setEmptyFields();

    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        saveClient();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        FrmMenu menu = new FrmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void saveClient() throws HeadlessException, NumberFormatException {
        String name;
        String lastName;
        int id;
        int age;
        String phoneNumber;
        String address;
        String gender;
        Client client;
        String email;

        name = txtName.getText();
        lastName = txtLastName.getText();
        phoneNumber = txtPhoneNumber.getText();
        address = txtAddress.getText();
        gender = getGender();
        email = txtEmail.getText();

        if (emptyValidation(gender)) {
            if (fieldsValidation(gender)) {
                id = Integer.parseInt(txtId.getText());
                age = Integer.parseInt(txtAge.getText());
                client = new Client(name, lastName, id, gender, age, phoneNumber, address, email);
                saveClientsDatabase(FileManager.serializationGson(client));
                JOptionPane.showMessageDialog(this, "El registro de ha realizado correctamente");
                setEmptyFields();
            }
        }

    }

    private boolean fieldsValidation(String gender) {

        setWarnings();
        boolean validation = true;
        JTextField txtGender = new JTextField(gender);

        ArrayList<JTextField> txtsCharacters = new ArrayList<>();
        ArrayList<JTextField> txtsNumbers = new ArrayList<>();

        txtsCharacters.add(txtName);
        txtsCharacters.add(txtLastName);
        txtsNumbers.add(txtId);
        txtsNumbers.add(txtAge);
        txtsNumbers.add(txtPhoneNumber);
        txtsCharacters.add(txtGender);

        for (int i = 0; i < txtsCharacters.size(); i++) {
            if (!InputValidation.validateCharacters(txtsCharacters.get(i).getText())) {
                getWarnings(txtsCharacters.get(i), txtGender);
                validation = false;
            }
        }

        for (int j = 0; j < txtsNumbers.size(); j++) {
            if (!InputValidation.isNumber(txtsNumbers.get(j).getText())) {
                getWarnings(txtsNumbers.get(j), txtGender);
                validation = false;
            }
        }

        if (validation == false) {
            JOptionPane.showMessageDialog(this, "Por favor, Llenar correctamente los campos ", "Error Fields", JOptionPane.WARNING_MESSAGE);
        }
        return validation;
    }

    private void setEmptyFields() {
        txtName.setText("");
        txtLastName.setText("");
        txtAddress.setText("");
        txtAge.setText("");
        txtPhoneNumber.setText("");
        txtId.setText("");
        chkMen.setSelected(false);
        chkWoman.setSelected(false);
        chkOthers.setSelected(false);
        txtEmail.setText("");

    }

    private void setWarnings() {

        lblWarningName.setVisible(false);
        lblWarningLastName.setVisible(false);
        lblWarningId.setVisible(false);
        lblWarningGender.setVisible(false);
        lblWarningAge.setVisible(false);
        lblWarningPhoneNumber.setVisible(false);
        lblWarningAddress.setVisible(false);
        lblWarningEmail.setVisible(false);

    }

    private String getGender() {

        String gender = "";

        if (chkMen.isSelected() && !chkOthers.isSelected() && !chkWoman.isSelected()) {
            gender = chkMen.getText();
        } else if (!chkMen.isSelected() && chkOthers.isSelected() && !chkWoman.isSelected()) {
            gender = chkOthers.getText();
        } else if (!chkMen.isSelected() && !chkOthers.isSelected() && chkWoman.isSelected()) {
            gender = chkWoman.getText();
        }

        return gender;
    }

    private void saveClientsDatabase(String jsonObject) {

        Document dc;
        DatabaseConnection connection;

        connection = new DatabaseConnection("Clients");
        dc = Document.parse(jsonObject);
        connection.getCollection().insertOne(dc);
    }

    private boolean emptyValidation(String gender) {

        setWarnings();
        JTextField txtGender = new JTextField(gender);
        boolean validation = true;
        ArrayList<JTextField> txts = new ArrayList<>();

        txts.add(txtName);
        txts.add(txtLastName);
        txts.add(txtId);
        txts.add(txtAge);
        txts.add(txtPhoneNumber);
        txts.add(txtAddress);
        txts.add(txtGender);
        txts.add(txtEmail);

        for (int i = 0; i < txts.size(); i++) {
            if (txts.get(i).getText().trim().isEmpty()) {
                getWarnings(txts.get(i), txtGender);
                validation = false;
            }
        }

        if (validation == false) {

            JOptionPane.showMessageDialog(this, "Por favor, Llene todos los campos ", "Error Empty Fields", JOptionPane.WARNING_MESSAGE);
        }

        return validation;
    }

    private void getWarnings(JTextField txtField, JTextField txtGender) {

        if (txtField.equals(txtName)) {
            lblWarningName.setVisible(true);
        } else if (txtField.equals(txtLastName)) {
            lblWarningLastName.setVisible(true);
        } else if (txtField.equals(txtId)) {
            lblWarningId.setVisible(true);
        } else if (txtField.equals(txtAge)) {
            lblWarningAge.setVisible(true);
        } else if (txtField.equals(txtPhoneNumber)) {
            lblWarningPhoneNumber.setVisible(true);
        } else if (txtField.equals(txtAddress)) {
            lblWarningAddress.setVisible(true);
        } else if (txtField.equals(txtEmail)) {
            lblWarningGender.setVisible(true);
        } else if (txtGender.getText().trim().isEmpty()) {
            lblWarningEmail.setVisible(true);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegisterClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkMen;
    private javax.swing.JCheckBox chkOthers;
    private javax.swing.JCheckBox chkWoman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWarningAddress;
    private javax.swing.JLabel lblWarningAge;
    private javax.swing.JLabel lblWarningEmail;
    private javax.swing.JLabel lblWarningGender;
    private javax.swing.JLabel lblWarningId;
    private javax.swing.JLabel lblWarningLastName;
    private javax.swing.JLabel lblWarningName;
    private javax.swing.JLabel lblWarningPhoneNumber;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
